### PR TITLE
added hook to add list of players to infected

### PR DESCRIPTION
**Pull request by TimGoll**
tested with priest and it works

### CODE REVIEW

**Comment by Alf21** [comment]
Ahj, i will rework this definitely ^^

**Comment by TimGoll** [comment]
Have fun! :D
What's bad about it?

**Comment by Alf21** [comment]
Inefficient networking, for loop with do-while behavior ^^

**Comment by TimGoll** [comment]
I did not know about other types of loops in lua :D 
But you're right with the networking part

**Pull request merged**
